# Name of workflow
name: test and linter

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true
  NODE_OPTIONS: --experimental-vm-modules

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
        # Check-out repository under GitHub workspace
      - uses: actions/checkout@v2
      # The Node.js version to configure
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test
